# .goreleaser.yml
before:
  hooks:
    - go mod tidy
kos:
  - repository: ghcr.io/findonflow/fluffy
    tags:
    - '{{.Version}}'
    - latest
    bare: true
    preserve_import_paths: false
    platforms:
    - linux/amd64
    - linux/arm64
